version: '3'
services:
  app:
    container_name: docker-node-dynamo
    restart: always
    build: .
    ports:
      - '8085:9001'
    links: 
      - dynamodb
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    environment:
      - AWS_ACCESS_KEY_ID= your_access-key_id
      - AWS_SECRET_ACCESS_KEY= your_secret_access_key
      - AWS_DEFAULT_REGION= your_region
    hostname: dynamodb
    restart: always